### ISSUE TITLE
Errors decoding CDR file

### ISSUE THREAD

**Issue by Saichovsky** [aenima-x/stockholm#1]
Hi,

I am having some problems when trying to decode a CDR file using this module. The scripts used and the errors generated can be viewed on this gist: https://gist.github.com/Saichovsky/f0f1f75fd23c288246b0

Any help given will be appreciated. Please pardon me if this is not an _issue_ but something that I could be doing wrong.

S.

**Comment by aenima-x** [comment]
Sorry man, I had a problem with the versions.
Checkout the new version and it should run ok.
Let me know

**Comment by Saichovsky** [comment]
Great. Thanks a lot. Let me try it out and let you know.

**Comment by Saichovsky** [comment]
Now Script1.py shows that get_cdrs_from_file has been removed from the module and Script2.py throws "ValueError: A primitive Tag can't be a CallDataRecord Tag 2".

I think you forgot to update the example.py file :-)

**Comment by aenima-x** [comment]
haha I really suck using git, you are right about the example, but when I did the merge I broke something else.
When I get home I will restore a backup. Because now not even my test CDR works.

**Comment by aenima-x** [comment]
the example is fixed and running.
If you still get the error the problem is with your CDR, keep in mind that I could not test it with a lot of different CDR files. Are you using Ericsson CDRS?
Can you send me a sample?
